builds:
  - binary: cai
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: cai
    homepage: "https://github.com/TomByte/commit-ai"
    tap:
      owner: TomByte
      name: homebrew-cai
    commit_author:
      name: TomByte
      email: tom@tombyte.com

checksum:
  name_template: 'checksums.txt'